version: "3"
services:
  backend1:
    image: owlplace
    command: /bin/server -members /tmp/owlplace.json
    ports:
      - "3001:3001"
    volumes:
      - "./docker-owlplace.json:/tmp/owlplace.json"
    environment:
      - "OWLPLACE_NODEID=1"
      - "OWLPLACE_ADDRESS=backend1"
    networks:
      - owlplace-network
  backend2:
    image: owlplace
    command: /bin/server -members /tmp/owlplace.json
    ports:
      - "3002:3001"
    volumes:
      - "./docker-owlplace.json:/tmp/owlplace.json"
    environment:
      - "OWLPLACE_NODEID=2"
      - "OWLPLACE_ADDRESS=backend2"
    networks:
      - owlplace-network
  backend3:
    image: owlplace
    command: /bin/server -members /tmp/owlplace.json
    ports:
      - "3003:3001"
    volumes:
      - "./docker-owlplace.json:/tmp/owlplace.json"
    environment:
      - "OWLPLACE_NODEID=3"
      - "OWLPLACE_ADDRESS=backend3"
    networks:
      - owlplace-network
networks:
  owlplace-network:
    driver: bridge
