name: build & test backend

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: build backend image
      run: make image
