name: build & test frontend

on: 
  pull_request:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install npm deps
      working-directory: ./client
      run: npm install
    - name: build site
      working-directory: ./client
      run: npm run build
    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        BUILD_SCRIPT: npm run deploy # The build script the action should run prior to deploying.
