name: build & test frontend

on: [push, pull_request]

jobs:
  build-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build site
      working-directory: ./client
      run: |
        npm install
        npm run build
    - name: deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
